#!/usr/bin/env bash

DIR="$(dirname "$(readlink -f "$0")")"

if [ -z "$1" ]; then
  echo "Error: Base branch is not provided."
  echo "Usage: ./amp-pr-create <base branch>"
  exit 1
fi
BASE_BRANCH="$1"

cat $DIR/pr-create.md | \
  sed "s|_branch_|$BASE_BRANCH|g" | \
  amp --interactive
