#!/usr/bin/env bash

DIR="$(dirname "$(readlink -f "$0")")"

# Reads ./03_process-task.md, replaces the below placeholders and pipes into `amp`

# - link_to_pr with LINK env var
# - reviewer_github_name with REVIEWER env var
# - path_to_comments_file with COMMENTS env var

## Example Usage (multiline):

# LINK=somelink \
# REVIEWER=someuser \
# COMMENTS=comments.md \
#   ./amp-pr0-03 <task number>

# 1. Check that all env vars are set

if [ -z "$LINK" ] || [ -z "$REVIEWER" ] || [ -z "$COMMENTS" ]; then
  echo "Error: Required environment variables LINK, REVIEWER, or COMMENTS are not set."
  # print usage
  echo "Usage: LINK=<link_to_pr> REVIEWER=<reviewer_github_name> COMMENTS=<path_to_comments_file> ./01_prepare.sh"
  exit 1
fi

# 2. Verify task_number was provided as first arg

if [ -z "$1" ]; then
  echo "Error: Task number is not provided."
  echo "Usage: ./amp-pr0-03 <task_number>"
  exit 1
fi
TASK_NUMBER="$1"

# 3. Run amp in interactive mode (to allow confirmations)
COMMENTS_SEPARATED="${COMMENTS%.md}.separated.md"
cat $DIR/03_process-task.md | \
  sed "s|link_to_pr|$LINK|g" | \
  sed "s|reviewer_github_name|$REVIEWER|g" | \
  sed "s|path_to_comments_separated|$COMMENTS_SEPARATED|g" | \
  sed "s|task_number|$TASK_NUMBER|g" | \
  amp --interactive
